[package]
name = "db_access_health"
version = "0.1.0"
authors = ["Taketomo Ohishi <takeweb@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rusqlite = "0.21"
