[package]
name = "date_util"
version = "0.1.0"
authors = ["Taketomo Ohishi <takeweb@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
jpholiday = "0.1.4"
