[package]
name = "mkdir"
version = "0.1.0"
authors = ["Taketomo Ohishi <takeweb@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
dotenv = "0.15.0"
my_lib = { path = "../my_lib" }
